// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-87r5PS_nk-LFDy-t96vISBFx0OOl3QQ',
    appId: '1:534994617194:web:a714ca1a325a820263db13',
    messagingSenderId: '534994617194',
    projectId: 'my-block-5c139',
    authDomain: 'my-block-5c139.firebaseapp.com',
    storageBucket: 'my-block-5c139.firebasestorage.app',
    measurementId: 'G-CMZ8FVMBF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHL0NP_gTCtmCEA-mSUD1wBm7wlgCb3Hg',
    appId: '1:534994617194:android:7473479a00ea26c963db13',
    messagingSenderId: '534994617194',
    projectId: 'my-block-5c139',
    storageBucket: 'my-block-5c139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpirZri9xBUMI9qdXseVutCiFnFF-UiUs',
    appId: '1:534994617194:ios:b726c523b114821563db13',
    messagingSenderId: '534994617194',
    projectId: 'my-block-5c139',
    storageBucket: 'my-block-5c139.firebasestorage.app',
    iosBundleId: 'com.example.myBlock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpirZri9xBUMI9qdXseVutCiFnFF-UiUs',
    appId: '1:534994617194:ios:b726c523b114821563db13',
    messagingSenderId: '534994617194',
    projectId: 'my-block-5c139',
    storageBucket: 'my-block-5c139.firebasestorage.app',
    iosBundleId: 'com.example.myBlock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-87r5PS_nk-LFDy-t96vISBFx0OOl3QQ',
    appId: '1:534994617194:web:24dff4bf70cca03d63db13',
    messagingSenderId: '534994617194',
    projectId: 'my-block-5c139',
    authDomain: 'my-block-5c139.firebaseapp.com',
    storageBucket: 'my-block-5c139.firebasestorage.app',
    measurementId: 'G-0XLLSM3NLS',
  );
}
